### ISSUE TITLE
Very small movement in header on iOS

### ISSUE THREAD

**Issue by alexpchin** [PedroBern/react-native-collapsible-tab-view#110]
When you pull down, and the content snaps back to the top for the first time, it moves the header upwards by about 1 or 2 px.  The next time you pull down, the header moves very slightly. 

Using `snapThreshold` of 0.5. Please see the video.

[simulator1.mov.zip](https://github.com/PedroBern/react-native-collapsible-tab-view/files/5957838/simulator1.mov.zip)

**Comment by andreialecu** [comment]
This is actually on purpose because of a weird interaction between the wrapper horizontal scrolling container (tab switcher) and the inner vertical ScrollView.

If the inner scrollview rests at the top (y === 0), you will not be able to pull to refresh. 

So we can't allow it to go to 0, but to `y: 1` instead.

Try changing this line:
https://github.com/PedroBern/react-native-collapsible-tab-view/blob/b9332342e1ce95a984cc95f1ba7e631dbbbbc074/src/hooks.tsx#L139

To:
```tsx
paddingTop: IS_IOS ? 1 : headerHeight + tabBarHeight,
```

(you can edit it in `node_modules` directly)

**Comment by andreialecu** [comment]
I did some brief testing and the changing that seems to work.

If you confirm, we can merge #112

**Comment by alexpchin** [comment]
@andreialecu I'll check now!

**Comment by alexpchin** [comment]
I've made the change locally as per #112 In the v3 version, there was no movement at all - it still seems to have a very small

**Comment by alexpchin** [comment]
I'm now not seeing this anymore since upgrading > rc.2. I will close.
