### ISSUE TITLE
What happen to the onScroll event?

### ISSUE THREAD

**Issue by MAgungHKM** [PedroBern/react-native-collapsible-tab-view#165]
All I see are onScrollBegin, onScrollEnd, onScrollAnimationEnded, etc

**Comment by andreialecu** [comment]
The library needs to handle `onScroll` itself in order to be able to work. There's a hook you can use that allows you to animate the header, see https://github.com/PedroBern/react-native-collapsible-tab-view/blob/main/example/src/AnimatedHeader.tsx

It may be possible to add another hook that provides access to the current scroll Y value.

What is your use case?

**Comment by Raden-Hor** [comment]
There any hook that I can access to onScroll Event to get scrollY of Tabs.Flatlist?
