### ISSUE TITLE
How can I detect that the user has reached bottom of Tabs.ScrollView?

### ISSUE THREAD

**Issue by timothygorer** [PedroBern/react-native-collapsible-tab-view#301]
I am trying to detect when user reaches bottom of Tabs.ScrollView so then I can load more data for pagination. It looks like the onScroll of Tabs.ScrollView is not firing. I am not quite sure why, but I suspect it has to do with the react-native-collapsible-tab-view containing another ScrollView inside it. I need to use Tabs.ScrollView because the refreshControl property works with it, but refreshControl doesn't work with Tabs.FlatList. I have seen the hook useCurrentTabScrollY() mentioned here before, but I am not sure how to correctly use this hook to detect if user has reached the bottom of the Tabs.ScrollView. Any advice would be highly appreciated.

**Comment by timothygorer** [comment]
Figured it out using Tabs.FlatList. Had to set the prop nestedScrollEnabled={true}.

**Comment by pfcodes** [comment]
interested in knowing how you did this? since `Tabs.ScrollView` is top level it can't exist inside its own component.

**Comment by acro5piano** [comment]
@timothygorer Did you find a solution?

**Comment by golu7679** [comment]
@timothygorer @acro5piano did you guys find a solution?

**Comment by acro5piano** [comment]
Wow this issue is long time ago.

I can't provide full code example because I was working for a proprietary project, but I would say `useCurrentTabScrollY` was helpful here.

```tsx
import { useCurrentTabScrollY } from 'react-native-collapsible-tab-view';

function MyComponent() {
  const scrollY = useCurrentTabScrollY();
}
```

Please note `scrollY` does not change even if user scrolls the tab - so you should force re-render the component (by `useState` + `setInterval` or something). That was the only successful way. Not sure for recent versions.

**Comment by golu7679** [comment]
@acro5piano Thank you so much
