### ISSUE TITLE
Define a minimum header hight

### ISSUE THREAD

**Issue by kiwina** [PedroBern/react-native-collapsible-tab-view#5]
Hi, love this plugin well written. 
I'm trying to make a header with several animated objects in it that fade out but some will stay. So far i have not figured out where the final offset is calculated to keep some of the header without closing it compleately

**Comment by PedroBern** [comment]
Hi @kiwina can you share some code or a screenshot?

**Comment by PentamapRainer** [comment]
Same here: How is it possible to set a minimum height of the remaining collapsible header so that there can be shown an ActionBar? It should look similar to that: 

![Simulator Screen Shot - iPhone 11 - 2021-01-07 at 13 58 28](https://user-images.githubusercontent.com/6825724/103895269-6d3cb400-50f0-11eb-8e80-23766422fba6.png)

**Comment by PedroBern** [comment]
Hi @PentamapRainer you can render the toolbar above the `CollapsibleTabView` and pass the same `Animated.Value` to both (<CollapsibleTabView animatedValue={scrollY} />)

I have a setup like this where I'm using a `react-navigation` header and animating the title when the user is scrolling.

**Comment by PentamapRainer** [comment]
When I try to render the toolbar above the `CollapsibleTabView` with following code, then the `CollapsibleTabView` is not shown any more. Just the `Text` element is shown.

```
<View>
    <Text>HERE COMES THE NAVIGATIONBAR</Text>        
    <CollapsibleTabView<Route>
        navigationState={{ index, routes }}
        renderScene={renderScene}
        onIndexChange={handleIndexChange}
        renderHeader={renderHeader}
        headerHeight={HEADER_HEIGHT}
        tabBarHeight={150}
        {...props}
    />
</View>
```

So where do I have to render the NavigationBar above the  `CollapsibleTabView`?

**Comment by PedroBern** [comment]
Did you try `flex: 1`?

**Comment by PentamapRainer** [comment]
> Did you try flex: 1?

Thanks a lot! That worked:

```
<View style={{flex:1}}>
    <Text>HERE COMES THE NAVIGATIONBAR</Text>
    <CollapsibleTabView<Route>
        navigationState={{ index, routes }}
        renderScene={renderScene}
        onIndexChange={handleIndexChange}
        renderHeader={renderHeader}
        headerHeight={HEADER_HEIGHT}
        tabBarHeight={150}
        {...props}
    />
</View>
```

**Comment by PentamapRainer** [comment]
One more question to this issue: Is it possible to make the collapsible header behind the (transparent) NavigationBar, so that the header image is visible behind the NavigtionBar when scrolling to the top.

This is how it looks now:

![Simulator Screen Shot - iPhone 11 - 2021-01-08 at 09 25 50](https://user-images.githubusercontent.com/6825724/103992152-fc4ed800-5193-11eb-8095-57c2d1c4c8ae.png)

This is how it should look like:

![Simulator Screen Shot - iPhone 11 - 2021-01-08 at 09 29 54](https://user-images.githubusercontent.com/6825724/103992239-17214c80-5194-11eb-898b-d1def5bb78fb.png)

**Comment by tcorreiaubi** [comment]
@PentamapRainer If I got your question right, you can interpolate the opacity of the "bar", to do so, you can use the animated value coming from the CollapsibleTabView and interpolate it between 0 and the header height to get the opacity, something like
`
  const backgroundOpacity = scrollYPosition.interpolate({
    inputRange: [0, scrollSize],
    outputRange: [0, 1],
    extrapolate: 'clamp',
  });
  `

**Comment by tcorreiaubi** [comment]
@PedroBern Is it possible to configure a minimum header height with the v3 version? While the approach of placing the component outside the Collapsible tab view component is an easy and simple approach, if you need to place the content with an absolute position on the header(something similar to the previous image on the comments), it becomes really hard to come with a solution since the absolute position removes the component from the screen flow and its size is not taken into consideration.
This is more of a discussion other than an "issue" for me, wasn't just sure how to reach you to discuss it, thanks in advance.

**Comment by PedroBern** [comment]
@tcorreiaubi no, it's still no possible in v3, I know, this desired configuration is probably hard to get with the current implementation, but it's open for PR.

The next milestones are adding a default tab bar (WIP), then integrate v3 with react-navigation.

Also, I'm planning to add something like `visibleHeaderOffset` into the context to get the visible delta and easily interpolate, for example, the backgroundColor/opacity of the header.
