### ISSUE TITLE
Header gets stuck if a tab doesnt have enough content

### ISSUE THREAD

**Issue by sniib** [PedroBern/react-native-collapsible-tab-view#8]
First of all, thanks for creating this awesome wrapper!

As you can see, when I scroll down the A tab and switch to B, the header gets stuck and there is empty space between the header and the content. I guess the expected behaviour would be that the header resets to max height when switching to tab B.

![Alt Text](https://media.giphy.com/media/zgj2qA3BrRVGpveESk/giphy.gif)

**Comment by andreialecu** [comment]
I'm also running into this and I'm curious how to solve it.

Since the user can see part of other tabs while swiping, I'm not sure how to visually handle this.

A potential solution might be to fix the gap up top so the tab content starts aligned to the top. Then once the gesture is released, the header might pop in and the tab content would move down.

**Comment by PedroBern** [comment]
The above commit fix it, but a customized `minHeight`, including the navigation bar and status bar height, would be a better solution but must be provided in-app, not in-package.
